"""empty message

Revision ID: 11281628dd0f
Revises: d40bf9b68384
Create Date: 2023-01-20 13:47:21.786364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11281628dd0f'
down_revision = 'd40bf9b68384'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('question_authority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'question_authority')
    # ### end Alembic commands ###
