"""empty message

Revision ID: ea8589d50a5f
Revises: 11281628dd0f
Create Date: 2023-01-20 14:27:06.290159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea8589d50a5f'
down_revision = '11281628dd0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('evaluation', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'evaluation')
    # ### end Alembic commands ###
