"""empty message

Revision ID: 02d278aa80e7
Revises: f21eafbb8554
Create Date: 2023-01-18 15:21:20.341610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02d278aa80e7'
down_revision = 'f21eafbb8554'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
