"""empty message

Revision ID: 465a1c6a7da8
Revises: 16e4990dd9dd
Create Date: 2023-01-18 14:56:08.336083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465a1c6a7da8'
down_revision = '16e4990dd9dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
