"""empty message

Revision ID: 7645da3bf6e1
Revises: c8b58c0529c1
Create Date: 2023-01-16 16:35:50.169985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7645da3bf6e1'
down_revision = 'c8b58c0529c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
