"""empty message

Revision ID: f21eafbb8554
Revises: 465a1c6a7da8
Create Date: 2023-01-18 15:15:37.055822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f21eafbb8554'
down_revision = '465a1c6a7da8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
